---
title: "Diferencias en la composición de sustrato entre Dzilam de Bravo y El Cuyo de la península de Yucatán"
author:
  - name: Sebastián Medina
    email: 319529818@enesmerida.unam.mx
    affiliations: 
      - id: some-tech
        name: ENES UNAM unidad Mérida
        department: Ecología de Campo VI
        address: Tablaje Catastral N°6998, Carretera Mérida-Tetiz Km. 4.5
        city: Ucú
        state: Yucatán
        postal-code: 97357
    corresponding: true
  - name: David Sánchez
    email: 420049609@enesmerida.unam.mx
    affiliations:
      - id: another-u
        name: ENES UNAM unidad Mérida
        department: Ecología de Campo VI
        address: Tablaje Catastral N°6998, Carretera Mérida-Tetiz Km. 4.5
        city: Ucú
        state: Yucatán
        postal-code: 97357
  - name: Diego Muñoz
    email: 317137150@enesmerida.unam.mx
    affiliations:
      - id: some-tech
        name: ENES UNAM unidad Mérida
        department: Ecología de Campo VI
        address: Tablaje Catastral N°6998, Carretera Mérida-Tetiz Km. 4.5
        city: Ucú
        state: Yucatán
        postal-code: 97357
abstract: |
  Los pastos marinos tienen una amplia distribución alrededor de la península de Yucatán y representan un pilar destacado para el sostenimiento de la fauna bentónica. No obstante, dicha distribución no es igual ni a lo largo de la costa ni mar adentro. A través de una versión modificada de la metodología AGRRA, caracterizamos y comparamos la composición de sustratos submareales entre dos localidades del norte de la península de Yucatán (Dzilam de Bravo y El Cuyo) a 20, 40 y 60 metros de la línea de costa. También exploramos la probabilidad de detección de la fauna macrobentónica en ambas localidades. Encontramos que, al menos en los primeros 60 metros de zona submareal, Dzilam de Bravo presenta una mayor diversidad de sustratos que El Cuyo y que estos varían en su composición en función de la distancia a la línea de costa. De los nueve sustratos registrados para Dzilam de Bravo, dos fueron especies de pastos marinos: *Thalassia testudinum* y *Syringodium filiforme*; creemos que la dominancia de la segunda indica procesos de sucesión ecológica temprana en la localidad. Por otro lado, la probabilidad de detección de fauna bentónica fue baja para Dzilam de Bravo (0.11 para bivalvos y 0.22 para gasterópodos) y nula para el Cuyo. Nuestros hallazgos secundan la heterogeneidad reportada en sustratos de pastos marinos a lo largo de la península de Yucatán.
keywords: 
  - Sustrato
  - Megabentos
  - Pastos marinos
  - Zona submareal
date: last-modified
bibliography: bibliography.bib
crossref:
  fig-title: Figura
  title-delim: .
  fig-prefix: Fig.
  labels: arabic
  subref-labels: alpha a 
format:
  elsevier-pdf:
    keep-tex: true
    journal: 
      name: Journal of Sea Research
      formatting: preprint
      model: 3p
      layout: twocolumn
      cite-style: authoryear
      
editor: 
  markdown: 
    wrap: 72
---

# Introducción

Las zonas costeras representan un foco de interés para la biodiversidad,
pues son la base de intercambio de materia biótica y abiótica entre los
ecosistemas terrestres y los marinos. Estas albergan una gran diversidad
de especies en los ecosistemas que la conforman, como los pastos
marinos. Estos están constituidos, principalmente, por una comunidad
vegetal bentónica [@herrera2019pastos] y se distribuyen a manera de
parches estratificados.

Para el caso de la península de Yucatán, se ha reportado una amplia
distribución de especies de pastos marinos, como *Thalassia testudinum,
Halodule wrightii*, *Syringodium filiforme* y *Ruppia mexicana,* por
mencionar algunas, siendo esta última una especie éndemica de la región
[@unknown]. Tal fenómeno se ha explicado por la poca profundidad que
tienen sus costas, lo cual permite niveles de irradiación óptimos para
los mismos en  regiones vastas. Además, Sánchez et al
[@sanchez2007analisis] propone que la composición calcárea del sustrato
favorece la fijación y colonización de las plantas macrófitas, lo que
propicia el crecimiento de una variada macroflora marina.

Los pastos marinos cumplen con diferentes servicios ecosistémicos como,
la captura de carbono, disipación de corrientes (lo que permite la
estructuración de las costas), reducción de las tasas de erosión costera
[@herrera2019pastos] y provisión de microhábitats para una gran
diversidad de organismos invertebrados considerados cómo fauna
bentónica. La fauna bentónica es toda aquella que se encuentra en el
fondo del agua y ha sido clasificada en diferentes tamaños:
microbentónica \<0.063 mm, meiobentónica 0.063--1.0 mm, macrobentónica
\>1.0 mm y megabentónica \> 10.0 mm [@tagliapietra2010benthic].
Organismos como oligoquetos, poliquetos, moluscos, gasterópodos,
bivalvos, crustáceos, etc., realizan funciones importantes dentro de  su
ecosistema.  Algunos cumplen con el papel de ser organismos
detritívoros, otros como filtradores de materia orgánica y demás.
Asimismo, también están ligados a redes tróficas como alimento para
especies de mayor tamaño [@tagliapietra2010benthic].

Continuar estudiando la composición de las zonas bentónicas submareales
es una tarea importante a realizar, ya que, de esta manera poder evaluar
y comprender los procesos ecológicos que se desarrollan en esos
ecosistemas en vistas de mejorar planes de manejo para la biodiversidad
marina. Es en este contexto que el propósito de nuestro trabajo es
caracterizar la composición del sustrato submareal y la composición de
fauna megabentónica en dos localidades, Dzilam de Bravo y El Cuyo a 20 ,
40 y 60 metros de la línea de costa. con el objetivo de comparar ambos
sitios utilizando una metodología AGRRA.

# Metodología

## *Área de estudio*

En este estudio contemplamos a Dzilam de Bravo y El Cuyo. El primero,
situado en el norte de Yucatán entre los paralelos 21°19' y 21°32' N y
los meridianos 88°35' y 88°58', limita al norte con el Golfo de México y
está influenciado en su circulación oceánica por los vientos y las
corrientes provenientes del canal de Yucatán, principalmente
[@1834/36164]. Además, presenta una diversidad de fondos en la que se
encuentran fondos arenosos, arenosos con conchuela, duros de lajas y
piedras [@1834/36164]. Por su parte, El Cuyo se sitúa en el paralelo
21°31' N y el meridiano 87°39', ubicado al noreste de la península
[@cnarioCuyo]. La costa presenta una pendiente reducida con arenas
combinadas de tamñaos medianos y pequeños, las corrientes llevan una
dirección Oeste-Noroeste, con velocidad promedio entre 0.7 y 0.8 nudos,
alcanzando velocidades máximas de hasta 3 nudos [@cnarioCuyo] (figura
1).

## *Descripción de métodos de campo*

![Mapa del área de estudio de Dzilam de bravo (figura superior
izquierda) y El Cuyo (figura superior derecha) y los sitios de
muestreo.](Mapa_dots3.jpg)

Empleando una versión modificada del protocolo AGRRA 2016-09-22 (Lang,
2016) para sustratos distintos a corales, demarcamos tres lineas de
muestreo paralelas a la playa, teniendo una separación de 20 m entre
cada una, dando una distancia total de 60 m a línea de costa. Cada línea
de muestreo contuvo tres transectos de 10 m separados por una distancia
de 20 m entre ellos; cada transecto fue marcado cada 10 cm a través de
una soga. Para la caracterización del sustrato, ocupamos una cámara Go
Pro versión 8 para grabar un video por transecto desde el inicio hasta
el final de la soga en el que se pudieran apreciar las marcas.
Posteriormente, tomamos en cuenta lo que yaciera cada 10 cm por debajo
de las marcas, identificamos el sustrato, según la composición las
especies vegetales asociadas al mismo. Por otro lado, para la
caracterización del megabentos submareal, ocupamos un cuadrante de 25 x
25 cm que colocamos en los metros 1, 3, 5, 7 y 9 de cada transecto y
aplicado a cada una de las distancias 20 m, 40 m y 60 m,
respectivamente. Dentro de cada uno de estos, observamos detenidamente
entre las macroalgas en búsqueda de animales bentónicos y registramos
tal acción en un video de 30 segundos como mínimo.

## *Procesamiento de datos*

Con los datos obtenidos mediante el protocolo de muestreo calculamos el
porcentaje de cobertura de diferentes especies de plantas marinas y
macroalgas para cada distancia de la costa. Posteriormente
estandarizamos los porcentajes (raíz cuarta) utilizando RStudio (versión
4.3.1). Despues se calculó una matriz de disimilitud de Bray-Curtis con
el paquete vegan [@manualR], con la cual se realizó un análisis de
escalamiento multidimensional (MDS) no métrico con la paqueteria MASS
[@BookR].

# Resultados

![Composición del sustrato por distancia. Dzilam de Bravo (triángulo);
El Cuyo (círculo).](MDS.JPG)

Las variables consideradas fueron tipos de sustrato por localidad y por
sitio, profundidad inicial por sitio y probabilidad de detección de
fauna bentónica por localidad.

Como se observa en la Figura 2, registramos una mayor diversidad de
sustratos en Dzilam de Bravo que en EL Cuyo. Estos varían parecen variar
en su composición en función de la distancia a la línea de costa. Se
aprecia que los sitios de las líneas de muestreo a 20 y 40 m son más
similares entre sí que aquellos del sitio 60 m. Respecto a la
profundidad del agua, ésta no fue muy disímil entre ambos sitios. Dzilam
de Bravo, contó con 0.5, 1.4 y 1.53 metros de profundidad para los
sitios 20, 40 y 60 metros, respectivamente. Por su parte, en El Cuyo se
registró 0.7 m, 1.2 m y 2 m de profundidad.

![Promedio general de sustratos de Dzilam de Bravo (azul) y El Cuyo
(rojo).](Promedio_sus_gen.jpg)

![Cobertura de sustratos de Dzilam de Bravo (azul) y El Cuyo (rojo). A)
Distancia de 20 m de la línea de costa; B) Distancia de 40 m de la línea
de costa; C) Distancia de 60 m de la línea de
costa.](Promedio_sustratos.JPG)

En torno a la diversidad de sustratos por localidad ((figura 3), Dzilam
de Bravo, estuvo representada por dos especies de pastos marinos
(Thalassia testudinum y Syringodium filiforme) y siete especies de
macroalgas (*Dictyota divaricata, Chaetomorpha linum, Halimeda monile,
Caulerpa verticillata, Caulerpa prolifera, Caulerpa mexicana* y *Ulvaria
oxysperma*), mientras que El Cuyo solo presentó arena. Cabe destacar
pero hemos considerado *D. divaricata* (aún cuando la misma no está
directamente asociada al sustrato) por su elevada cobertura. Ahora bien,
respecto a la dominancia de tales sustratos en el sitio, se puede
apreciar en la figura 4 que el sustrato con mayor cobertura fue *S.
filiforme*, seguido por *D.divaricata*. No obstante, tal proporción
difirió por sitio. El sitio a 20 metros fue dominado por *D. divaricata*
seguida por *C. prolifera*, el sitio a 40 metros por *S. filiforme* casi
por completo y el sitio a 60 metros por *S. filiforme* seguida por *T.
testudinum*.

![Vegetación bentónica de Dzilam de Bravo. A) *Halimeda monile*; B)
*Thalassia testudinum*; C) *Syringodium filifiorme*; D) *Chaetomorpha
linum*; E) *Caulerpa prolifera.*](Especies_algas.JPG)

Finalmente, respecto al megabentos en Dzilam de Bravo, la probabilidad
de detección de bivalvos fue de 0.11 mientras aquella de gasterópodos
fue de 0.22. Cabe destacar que sólo obtuvimos valores para estos grupos
dado que no registramos otros taxones. Por su parte, no hubo registro de
ningún organismo en El Cuyo.

# Discusión

Las diferencias en la composición del sustrato entre Dzilam de Bravo y
El Cuyo son amplias, pues los resultados parecen reflejar tanto una
mayor diversidad en las especies asociadas al sustrato como una mayor
variación entre estas en función de la distancia a la línea de costa. En
este marco, mientras que en Dzilam de Bravo se registraron dos especies
de plantas marinas y siete especies de algas, en El Cuyo el único
sustrato registrado fue arena. Inicialmente, parecería que nuestros
resultados son contradictorios con la diversidad de macroalgas
reportadas en El Cuyo por Aguilar-Trujillo, et al.
[@aguilar2014variacion] o los pastos marinos identificados en el norte
de la Península por Herrera-Silveira et al. en el libro de Biodiversidad
y Desarrollo humano de Yucatán [@garcia2010biodiversidad]. No obstante,
es posible que las distancias que hemos considerado en el muestreo de El
Cuyo no hayan sido suficientes para abarcar zonas submareales con
sustratos distintos a la arena. Por tanto, a partir de nuestros
resultados, no podemos concluir información más allá de que en los
primeros 60 m a partir de la línea de costa, el Cuyo cuenta con arena
como sustrato único mientras que en Dzilam de Bravo existe una
diversidad de sustratos constituida por pastos marinos y macroalgas.

Las causas para tal contraste entre ambos sitios pueden ser variadas.
Debiéndose al establecimiento de la vegetación acuática, Calva-Benítez y
Torres Alvarado [@calva2011carbono] refieren que tanto la cobertura como
la distribución de ésta yacen determinadas por la salinidad, la luz, la
temperatura, el tipo de sedimento, la fuerza del viento y la cantidad de
materia orgánica disuelta y particulada. Por su parte, Robbins y Bell
[@robbins2000dynamics] sugieren que la distribución de los pastos
marinos también puede ser explicada por: características fisiológicas y
de crecimiento, impactos del pastoreo, interacciones de competencia, la
hidrodinámica del sitio, bioturbación, el tamaño de grano del sedimento
y la profundidad del agua. Si bien nuestros resultados sugieren la
última no representa una variable determinante para razonar las
diferencias observadas, es recomendable medir más variables como las
previas en aras de entender por qué en el Dzilam de Bravo sí existen
pastos marinos en los primeros 60 metros a partir de la línea de costa
mientras que en el Cuyo no.

Con base base a lo anterior, la diversidad de sustratos en Dzilam de
Bravo podría dar indicios de la etapa sucesional en la que se
encuentran, al menos, los primeros 60 metros de la zona submareal. Dada
la alta cobertura S. filiforme, una especie pionera y oportunista como
lo refieren Álvarez-Sánchez et al. (2021), respecto a la de T.
testudinum, podríamos sugerir que la zona submareal en cuestión está en
un proceso de sucesión temprana. La baja detección de organismos del
macrobentos podría estar asociada a tal proceso. Por otro lado, nuestros
resultados son concordantes con la literatura, pues observamos una mayor
cantidad de algas en los sitios con menor cobertura de fanerógamas
marinas [@sanchez2021cobertura] y detectamos diferencias en la
diversidad de sustratos entre las localidades estudiadas
[@garcia2010biodiversidad].

\
Sustratos como los pastos marinos son fundamentales para el
sostenimiento de la fauna bentónica y la provisión de servicios
ecosistémicos variados. Bajo una modificación de la metodología AGRRA,
caracterizamos y comparamos la composición de sustratos en dos
localidades del norte de la península de Yucatán y exploramos la
probabilidad de detección de la fauna megabentónica. Encontramos que  al
menos en los primeros 60 metros de zona submareal, Dzilam de Bravo
presenta una mayor diversidad de sustratos que El Cuyo y que estos
varían en su composición en función de la distancia a la línea de costa.
Asimismo, sugerimos que la dominancia de S. filiforme en Dzilam de Bravo
subyace un proceso temprano de sucesión ecológica.  Por otro lado, la
probabilidad de detección de fauna bentónica fue baja para Dzilam de
Bravo (probablemente debido a la supuesta etapa de sucesión) y nula para
el Cuyo. Nuestros hallazgos secundan la heterogeneidad reportada en
sustratos de pastos marinos a lo largo de la península de Yucatán y
coinciden con la literatura hasta la fecha.

# Agradecimientos

Agradecemos al Dr. Edlin Guerra y la Dra. María del refugio por su
enseñanza, paciencia, alimentación y cuidadosa planeación del curso y
por el financiamiento de la salida de campo. 

# References {.unnumbered}
